version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdfdownloader_backend
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      # Map the local ./downloads directory to /app/downloads inside the container
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1 # Ensures Python logs appear directly
    command: ["poetry", "run", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdfdownloader_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501" # Streamlit's default port
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://backend:8000
      - PYTHONPATH=/app
    command: ["poetry", "run", "streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"] 